### ISSUE TITLE
Generalise nexus-prisma plugin

### ISSUE THREAD

**Issue by otrebu** [graphql-nexus/nexus-plugin-prisma#129]
Hi all!

I was thinking it would be great if this plugin was based on another more generic nexus plugin.

I am personally in a scenario where I would like to:

- Starting from an existing private graphql server.
- Generate the graphql-bindings for that server.
- Using a `nexus-prisma` approach to extend, hide, expose types from that private graphql server.
- Having my public graphql server up an running.

**Comment by Weakky** [comment]
Hey there 👋,

Thanks for this issue. While we generally like the idea, it's unfortunately not a priority for us at the moment. We’d be happy to switch out the underpinnings of nexus-prisma for something more general if there’s a good system available to do so.

Using the `prisma-client` offers us a lot of built-in optimizations that we'd have to re-develop inside nexus-prisma if we made it more generic.

This is not something unrealistic for the future though 🙌

**Comment by otrebu** [comment]
Hi @Weakky, thanks for listening to my suggestion.
I haven't had the time to familiarise myself yet with your codebase, but I would like to.

With your knowledge, do you think it would take long to take the current `nexus-prisma` plugin and make it more generic? 
Would you mind if I were to try that?

**Comment by otrebu** [comment]
@Weakky @nikolasburk sorry to tag you twice in a row.
Would you mind me try to work on this more generic nexus plugin? 
Starting from this codebase. Any tips on suggestion if I embark on this project?

**Comment by Weakky** [comment]
Hey @otrebu,

If you want to start working on a generic nexus plugin, feel free to do so. Most of the stuff you'll have to change is in `resolvers.ts`

**Comment by jasonkuhrt** [comment]
Hey @Weakky @otrebu, I'm not sure I see something actionable here for nexus-prisma. IIUC the discussion is about if we could extract a common plugin core, and then rebase `nexus-prisma` over it, but now allowing other `neuxs-*` plugins too. A few things have changed since this issue opened:

- Prisma v2
- Nexus Plugins (wip)

I feel the right place for this discussion is at the nexus level:

- https://github.com/prisma/nexus/pull/200
- https://github.com/prisma/nexus/issues/98

Please re-open if my conclusion is misguided!
