### ISSUE TITLE
Parent Arg in Resolvers don't expose nested fields

### ISSUE THREAD

**Issue by jaredjasonpeters** [graphql-nexus/nexus-plugin-prisma#155]
### I was planning to implement a dataloader for recurring queries such as 
```
{
  user(input: {id: "cjsktbe8r5xpz0b86a0le6efk" }){
    name
    email
    posts {
      author{
        posts {
          author{
            posts{
              author{
                posts{
                  title
                }
              }
            }
          }
          }
        }
      }
    }
  }
```
#### I only get following properties of the parent exposed
```
(parameter) post: {
    content?: string | null | undefined;
    createdAt: any;
    id: string;
    published: boolean;
    title: string;
    updatedAt: any;
}
```
```
const Post = prismaObjectType({
  name: "Post",
  definition: t => {
    t.prismaFields(["*"]);
    t.field("author", {
      type: "User",
      resolve: async (post, args, ctx) => {
        const author = await ctx.loaders.load(post.author.id)
        return author;
      }
    });
```
### I'm fairly new to using dataloaders, however I have implemented similar dataloaders based on mongoose and a mongodb database.

Thanks for any help to resolve this issue.

**Comment by Weakky** [comment]
Hey there,

By default, `prisma-client` only fetches scalar fields (for performance reasons), hence why you're not receiving `post.author.id` because `author` is a 1-1 relation.

If you want to force fetching the author id from the parent, you need to use the `$fragment` API

I have just given a very similar answer to #184. It shows how to use fragment to pass more data to the children resolvers, and how to keep type-safety.

We're aware this is not ideal at all, bear with us until until https://github.com/prisma/rfcs/blob/new-ts-client-rfc/text/0000-new-ts-client.md lands, which will give you a lot more flexibility and easiness to select what fields you want to fetch.

I'm closing now, feel free to re-open if that doesn't answer your question properly 🙏
