### ISSUE TITLE
mongo dependencies

### ISSUE THREAD

**Issue by tanekim88** [graphql-nexus/nexus-plugin-prisma#156]
Is nexus-prisma compatible with mongo version of prisma?
It would be helpful if there is an example repo that has mongo + nexus working

**Comment by Weakky** [comment]
Hey there,

Now that #157 is fixed, `nexus-prisma` should be properly compatible with mongo.

Providing an example shouldn't be useful as there are no difference in how you use `nexus-prisma` with mongo or postgres or mysql. Everything is abstracted for you so that you don't have to care about that. The only difference will be in the generated schema, which is something related to prisma and not to `nexus-prisma`.

The example, for instance, should work as it is with mongo. All you need to figure out is how to deploy prisma with mongo, which is something that is documented on the prisma documentation 🙂
