### ISSUE TITLE
Invalid prisma.yml file: Missing `generate` property for a `prisma-client`

### ISSUE THREAD

**Issue by SulimanTwfiq** [graphql-nexus/nexus-plugin-prisma#168]
Hello,
I was following " Using [GraphQL Nexus with a Database](https://www.prisma.io/blog/using-graphql-nexus-with-a-database-pmyl3660ncst/) " tutorial and i stuck in prisma deploy step with this problem 
![problem](https://user-images.githubusercontent.com/32466357/53690481-4dae0500-3d7c-11e9-819a-7a0f05c9d053.PNG)
This is my prisma.yml
![prismauaml](https://user-images.githubusercontent.com/32466357/53690488-76ce9580-3d7c-11e9-9610-a5a042c0c65c.PNG)
Any help , please ?

**Comment by Weakky** [comment]
Hey there,

Like the error says, you need to have a `generate` property in your prisma.yml to generate your `prisma-client`.

Check the `prisma.yml` of the example

https://github.com/prisma/nexus-prisma/blob/93588c0753038be6de7de4abc35db2c1faae0fb3/example/prisma/prisma.yml#L3-L10

We indeed need to better the documentation around that because it's not clear.

Thanks for reporting 🙏

**Comment by SulimanTwfiq** [comment]
Great thank you for replying , but now it stuck without any error or any genereated files .
 I don't know if its my PC problem or nexus problem.
![runningnpx](https://user-images.githubusercontent.com/32466357/53750488-f498bb00-3eba-11e9-8df2-5f7b5672bb02.PNG)

**Comment by vasco3** [comment]
@Weakky your solution fixed my problem. And for me it did generate files. Thank you
btw, In the output path you added an two dots in the relative path instead of one.
