### ISSUE TITLE
Generated types missing relations possibly

### ISSUE THREAD

**Issue by DevanB** [graphql-nexus/nexus-plugin-prisma#234]
I'm unsure if this is a nexus-prisma issue, an issue at all, or if I am perhaps misunderstanding something.

I have the following `User` type in my `datamodel.graphl`

```
type User {
  id: ID! @unique
  email: String! @unique
  firstName: String!
  lastLogin: DateTime
  lastName: String!
  organization: Organization! @relation(name: "UsersByOrganization")
  password: String!
  roles: [Role!]! @relation(name: "RolesByUser")
  settings: [Setting!]! @relation(name: "SettingsByUser")
  subscription: StripeSubscription @relation(name: "StripeSubscriptionByUser")
}
```

When I do the following in my server:

```
const updatedUser = await this.ctx.prisma.updateUser({
	data: {
    	lastLogin: new Date().toISOString(),
        updatedBy: { connect: { id: user.id } },
	},
    where: { id: user.id },
});
```

I expect to find that `updatedUser` would have a `roles` value, however it doesn't. It also seems to be missing `organization`, `settings` and `subscription`, which are all relationships.

The `User` interface (even after running `prisma generate` several times) is in fact:

```
export interface User {
  id: ID_Output;
  email: String;
  firstName: String;
  lastLogin?: DateTimeOutput;
  lastName: String;
  password: String;
}
```

Am I misunderstanding relationships, or is my generated types missing fields for a reason? 

Thanks much! 😄

**Comment by difagume** [comment]
The same thing happens to me, I'm using: `nexus: 0.11.6, nexus-prisma: 0.3.5, prisma-client-lib: 1.30.0, typescript: 3.4.2, ts-node: 8.0.3`

for example in my scheme I have:
```
type Articulo_detalle {
  activo: Boolean!
  articulo: Articulo!
  cantidad: Int!
  id: ID!
  producto: Producto!
}
```

but by looking at the file nexus.js I have:

```
Articulo_detalle: { // root type
    activo: boolean; // Boolean!
    cantidad: number; // Int!
    id: string; // ID!
  }
```

as well as in the index.ts file of the `generated/prisma-client` directory:
```
export interface Articulo_detalle {
  id: ID_Output;
  cantidad: Int;
  activo: Boolean;
}
```

The relationship to `Producto` is being lost.

**Comment by Weakky** [comment]
Hey 👋,

This is related to the prisma-client rather than nexus-prisma. But yeah, it's expected that `roles` aren't fetched by default because it's a relation, and the client only fetches scalar values by default.

- You either need to do `prisma.updateUser().roles()`
- or with GraphQL, returning a User in your top query will then pass that data to the resolvers of the `User` type, and if you have a `User.roles` resolvers, it will be resolved by doing `prisma.user({ id: root.id }).roles()`

The only way to fetch relations and scalars right now is by using fragments until the client V2 API lands: https://github.com/prisma/rfcs/pull/2

Hopefully that answers your question. If it doesn't, feel free to re-open 🙌

**Comment by DevanB** [comment]
I believe I understand this. Re: using fragments...is this what you have done [here](https://github.com/prisma/prisma-ecommerce-reference/blob/chore/refactor-with-yoga/packages/server/src/fragments/ProductVariant.ts) and [here](https://github.com/prisma/prisma-ecommerce-reference/blob/chore/refactor-with-yoga/packages/server/src/graphql/Collection.ts#L71)?

Thanks for the information @Weakky!
