### ISSUE TITLE
Not possible to create custom input types

### ISSUE THREAD

**Issue by akoenig** [graphql-nexus/nexus-plugin-prisma#235]
When defining own input types within a resolver which returns a Prisma type (`Box`) the following problem occurs:

```
src/mutations/createBox.ts:31:11 - error TS2322: Type 'NexusInputObjectTypeDef<"CreateBoxInput">' is not assignable to type 'NexusArgConfigType<"Int" | "Float" | "String" | "BoxImageWhereInput" | "BoxImageWhereUniqueInput" | "BoxVolumeWhereInput" | "BoxVolumeWhereUniqueInput" | "BoxWhereInput" | "BoxWhereUniqueInput" | ... 9 more ... | "ID">'.
  Type 'NexusInputObjectTypeDef<"CreateBoxInput">' is not assignable to type 'NexusInputObjectTypeDef<"Int" | "Float" | "String" | "BoxImageWhereInput" | "BoxImageWhereUniqueInput" | "BoxVolumeWhereInput" | "BoxVolumeWhereUniqueInput" | "BoxWhereInput" | "BoxWhereUniqueInput" | ... 9 more ... | "ID">'.
    Type '"CreateBoxInput"' is not assignable to type '"Int" | "Float" | "String" | "BoxImageWhereInput" | "BoxImageWhereUniqueInput" | "BoxVolumeWhereInput" | "BoxVolumeWhereUniqueInput" | "BoxWhereInput" | "BoxWhereUniqueInput" | ... 9 more ... | "ID"'.
```

![Screenshot from 2019-04-06 21-24-57](https://user-images.githubusercontent.com/224910/55674300-4914c900-58b3-11e9-8688-59c8ea5bac83.png)

**Comment by P4sca1** [comment]
Try to declare it at the root level and don’t forget to start your server one time so that the types get generated.

**Comment by Weakky** [comment]
Doing it like so should never be done anyway as you won't be able to pass your input type in the `makeSchema.types` property.

As advised by @P4sca1, extract your input type in the module scope, then reference it for your `input` argument, and don't forget to export it to also reference it in the `makeSchema` function so that graphql knows about this type 🙏

Closing now, feel free to re-open if that doesn't solve your problem
