### ISSUE TITLE
Cannot use mutation arguments as is with prisma client when using custom resolver

### ISSUE THREAD

**Issue by iamsuneeth** [graphql-nexus/nexus-plugin-prisma#287]
I am following nexus-prisma section of nexus docs for creating a custom resolver. The below code is suggested by the docs.

```
const Query = prismaObjectType({
      name: 'Query',
      definition(t) {
        t.field('users', {
          ...t.prismaType.users,
          resolve(root, args, ctx) {
            // Custom implementation
          },
        })
      },
    })
```

But when I pass arguments as it to prisma client mutation, it is giving type errors. The errors are mostly related to id attribute being optional in connect/create. Please find the code and error below

```
export const Mutation = prismaObjectType({
  name: 'Mutation',
  definition(t) {
    t.prismaFields({
      filter: ['createAttribute', 'createVariant', 'createOptionValue'],
    });
    t.field('createProduct',{
     ...t.prismaType.createProduct,
      resolve:(root,args,{prisma}) => {
        prisma.createProduct(args.data);
      }
    })
  },
})
```

Error received: 
```
Type '{ id?: string; }' is not assignable to type 'Pick<{ id: ID_Input; }, "id">'.
                                        Property 'id' is optional in type '{ id?: string; }' but required in type 'Pick<{ id: ID_Input; }, "id">'.
```

**Comment by tafelito** [comment]
I'm having the same issue but when I try to use the same arguments

```js
    t.field("ordersCount", {
      type: "Int",
      args: {
        ...t.prismaType.ordersConnection.args,
      },
      resolve: async (_, args, ctx) => {
        const { count } = await ctx.prisma.ordersConnection(args).aggregate();
        return count;
      },
    });
```

the error says `Type 'null' is not assignable to type 'OrderWhereInput | undefined'.t`

**Comment by Tydax** [comment]
@tafelito I think your issue is similar to [#3774](https://github.com/prisma/prisma/issues/3774)

Any updates on this please? I have the same issue as @iamsuneeth. For now, the only I found to make it work is rewriting my `where` argument to force `id` being required, or to cast my `data` to be the same type as Prisma's. I don't know if it's related, but I find it odd that the input types (both GraphQL and TypeScript) that Nexus generates like `FooWhereUniqueInput` do not require `ID` by default. Did I miss something in my configuration?
