### ISSUE TITLE
Nested filter on related model not working

### ISSUE THREAD

**Issue by iherger** [graphql-nexus/nexus-plugin-prisma#331]
(Prisma2/nexus)

I am using the following (simplified) model:
```graphql
model Staff {
  id         String       @default(cuid()) @id @unique
  user       User?
  active     Boolean?
}
model User {
  id         String        @default(cuid()) @id @unique
  email      String        @unique
  staff      Staff?
}
```
Using photon, the following query works:
```ts
  const staff = await photon.users.findMany({
    where: {
      staff: { active: true },
    },
  });
```
However, the following graphql query, exposed through nexus-prisma, fails:
```graphql
query {
  findManyUser(
    where: { staff: { active: true } }
  ) {
    id
    email
  }
}
```
with the error message:
```
Field "active" is not defined by type QueryFindManyUserWhereInput.
```
The nexus-prisma type generation seems to be incorrect, `active` should not be of type `QueryFindManyUserWhereInput`, I think.

**Comment by iherger** [comment]
@jasonkuhrt this is also quite an important bug to fix for nexus-prisma to work with prisma2. 

It's currently impossible to filter on related fields in nexus-prisma, but I think this is needed for many GraphQL queries. The actual photon query works, but nexus-prisma does not generate the correct types.

If you want to give me some pointers where to start looking in the nexus-prisma code, I can also try to investigate myself.

**Comment by jasonkuhrt** [comment]
@iherger would love to. In a few weeks/months from September onward (when I start full time) I could. But not yet 😅.

But rest assured this is high priority. Will loop back once I've had time to get more into this issue. Should be within a couple of weeks max.

**Comment by jasonkuhrt** [comment]
@iherger if you can put up a repro repo, that would help 🙏

**Comment by iherger** [comment]
Thanks, @jasonkuhrt . 

Here is a repro repo: https://github.com/iherger/nexus-prisma-nestedfilter

After installing, run 
```
yarn seed
yarn test
```
This should show that the following photon query works without problems:
```typescript
  const users = await photon.users.findMany({
    where: { staff: { active: { equals: true } } }
  });
```
Now, when you start the server (`yarn start`), and run the following query:
```graphql
{
  findManyUser (where: {staff: {active: {equals: true}}}) {
    email
  }
}
```
it fails with the error message `Field "active" is not defined by type QueryFindManyUserWhereInput.

I now realise that this is probably not such a common use-case (filtering on 1-1 relations), but it's still a bug...

The much more common use-case is #354, which deservers attention first.

**Comment by jasonkuhrt** [comment]
Thanks so much. Yeah working on a fix for that one.

**Comment by Weakky** [comment]
Reposting comment from #345:

Thanks @iherger for your reproduction. I could easily target the problem here.

@jasonkuhrt As a side-effect of the filtering and ordering arguments customization (eg: `t.crud.posts({ filtering: { id: true, author: true } })`), nexus-prisma needs to come up with inputs names scoped to their parent type + field name

eg: By default, given a `User` output type, we might have a `UserWhereInput` input type.
But because we can customize it everywhere, nexus-prisma aliases it to `QueryUsersWhereInput` for such a schema 

```graphql
type Query {
  users(where: QueryUsersWhereInput): [User!]!
}
```
(type name: `Query` + field name: `users` = `QueryUsers`)

The issue occurs for some of the fields of `QueryUsersWhereInput`.
- For the `AND` and `OR` fields, we can reference the same type `QueryUsersWhereInput`, so no issue.
- For the `String/Int/BooleanFilter` types, there is no issue either as nexus-prisma only allow to customize input types on one level of depth.
- The problem lies with relational filters inside `QueryUsersWhereInput` 👇

```graphql
type Query {
  users(where: QueryUsersWhereInput): [User!]!
}

input QueryUsersWhereInput {
  id: StringFilter
  AND: [QueryUsersWhereInput]
  OR: [QueryUsersWhereInput]
  post: WhatShouldBeTheNameOfThisType?? <--
}
```

At the moment, `QueryUsersWhereInput.post` is of type `QueryUsersWhereInput` too, which is the cause of the problem. It should be of type `PostWhereInput`, but I'm not sure yet whether we should alias these types as well or not.

Because we can only customize on one level of depth, the type of the field `QueryUsersWhereInput.post` won't ever be customized anyway. However, having input type's names scoped to their parent type name + field name for top-level field arguments, but not for the fields of input types makes the input type's names less predictable.

On the other hand, aliasing the types of fields of input types (eg: `QueryUsersWhereInput.post`) will create a lot more clutter/confusion in the final schema

We need to make a decision or find another approach to solve the problem.

PS: Let's fix #396 while solving this issue

**Comment by jasonkuhrt** [comment]
> but not for the fields of input types makes the input type's names less predictable.

> On the other hand, [...] will create a lot more clutter/confusion in the final schema

Cannot say with high confidence but I would aim for less cluttered schema right now. Wouldn't be surprised if this were not the optimal choice though. In fact it may depend on app case-by-case, the schema patterns in use, etc. I'm weary to over-design before getting more feedback and real-world examples.

----

> find another approach to solve the problem

I think we can close this issue with the `PostWhereInput` solution you've identified. However I have more thoughts, very likely falling out of scope and into a potential future feature.

You mention:

> As a side-effect of the filtering and ordering arguments customization [...] nexus-prisma needs to come up with inputs names scoped to their parent type + field name

> Because we can only customize on one level of depth, the type of the field QueryUsersWhereInput.post won't ever be customized anyway

Users _can_ customize top-level `Input` Object. However they might not. When they do not, qualification (namespacing) is not needed.

Users _cannot_ customize nested `Input` Objects. But maybe one day they can. At that time we would need to revisit qualification namspacing.

My point is, we don't need a static decision here. We can dedupe and namespace in accordance with what is actually going on in the user's codebase. Furthermore, we can expose config tuning for these mechanisms, not unlike the ideas in #169. So for example if a user wants maximum dedupe they can, or conversely if they want maximum qualification, they can.

So, I guess what I'm trying to say is, the decision between:

> but not for the fields of input types makes the input type's names less predictable.
> ...
> On the other hand, [...] will create a lot more clutter/confusion in the final schema

is not so significant, as I think we achieve:

>  find another approach to solve the problem.

But later.

Make sense?

**Comment by Weakky** [comment]
> Users cannot customize nested Input Objects. But maybe one day they can. At that time we would need to revisit qualification namespacing.

We originally went with the current solution (everything aliased) for consistency/predictability with namings and in anticipation that we might indeed allow one day for nested input object types customization, in which case changing the naming strategy would result in a breaking change.

Now that I realize how much clutter it’d create if it was properly implemented, I tend to agree with your solution (aliasing only if an input type is customized), in combination with the idea of dedupe vs qualification config tuning

Side note: It'll, however, make #396 partially impossible, as we won't be able to pre-alias all input types because it'll depend on the users' input. It'll still be possible for field names though, and shouldn't be a blocker anyway

**Comment by jasonkuhrt** [comment]
> aliasing only if an input type is customized

I could see this leading to more churn in the GQL schema. Three example mutually-inclusive ways I see giving users control over this, if it becomes a problem:

1. Config tuning (always qualify)
2. Composable input types DSL (maybe...)

```ts
import { WhereInput } from '@generated/nexus-prisma'

export default objectType({
  name: 'User',
  args: {
    // New DSL features here
    name: WhereInput({ name: 'MyWhatever', ... })
  },
  definition(t){
    t.model.name()
  }
})
```
3. Localized config tuning 
```ts
export default objectType({
  name: 'User',
  definition(t){
    t.model.name({ inputNaming: { where: "MyWhatever" } })
  }
})
```
