### ISSUE TITLE
Add support for new Pagination model introduced in prisma 2.0.0-beta7

### ISSUE THREAD

**Issue by divideby0** [graphql-nexus/nexus-plugin-prisma#677]
The latest Prisma 2 beta introduced a breaking change in the way that pagination works:

https://github.com/prisma/prisma-engines/pull/767

This appears to break the Nexus Schema plugin in at least one place:

https://github.com/graphql-nexus/nexus-schema-plugin-prisma/blob/master/src/typegen.ts#L238-L244

I'd be happy to help resolve this in my spare time, but I worry a naive change could break clients on a pre-beta7 version of the Prisma engine. Are there any existing mechanisms or precidents to change the behavior of typegen based on the version of the engine linked in the project?

**Comment by Gomah** [comment]
@jasonkuhrt @Weakky Any reasons why the `next` version reverted the new pagination schema?

It feels weird to have different pagination naming within the query engine & the GraphQL schema, e.g:

```ts
export const PublicUser = objectType({
  name: 'PublicUser',
  definition(t) {
    t.model('User').id();
    t.model('User').username();
    t.model('User').products({
      ordering: true,
      filtering: true,
      pagination: true,
      resolve: ({ id }, _args = {}, ctx) => {
        return ctx.prisma.product.findMany({
          ..._args,
          where: {
            owner: {
              id,
            },
          },
        });
      },
    });
  },
});
```

Generates:

```gql
type PublicUser {
  id: String!
  username: String!
  products(after: ProductWhereUniqueInput, before: ProductWhereUniqueInput, first: Int, last: Int, orderBy: ProductOrderByInput, where: ProductWhereInput): [Product!]!
}
```

However, the `arguments` passed into my custom resolve functions under `User.Products` won't match as the query engine now uses a different pagination model.

**Comment by jasonkuhrt** [comment]
@Gomah the reason is that we're moving towards relay pagination by default.

The mismatch you're experiencing could be remedied by a utility function that makes the conversion.

We might ship such a function in the future.

We're also open to a configurable pagination strategy system.

But such a system requires upstream work in Nexus. Specifically, the pagination strategy needs to be shared between Nexus and plugins. The goal being API consumers don't deal with multiple pagination styles.

Feature request welcome!
