### ISSUE TITLE
Question: case when we want explicite schema delegation and integration with prisma-binding

### ISSUE THREAD

**Issue by AMO-MTSY** [graphql-nexus/nexus-plugin-prisma#81]
Hello,
Question, please: 

On a note on prisma-binding read-me: Unless you explicitly want to use schema delegation we recommend to use Prisma client to build a GraphQL server. I see your are taking the whole thing to a new level with nexus and nexus prisma.

What about the case when we want explicite schema delegation? Can we use nexus-prisma and/or nexus wirth prisma-binding?

**Comment by AMO-MTSY** [comment]
Got a response from a comment on nexus blog article.
"GraphQL Nexus is a GraphQL schema construction library that is independent from Prisma. There's no need to migrate to it if you're currently using a different approach (such as SDL-first based on graphql-tools). That being said, we're working on a plugin that will enable a nice integration of Nexus and the Prisma client, we'll publish a blog post about it very soon."
source: https://www.prisma.io/blog/introducing-graphql-nexus-code-first-graphql-server-development-ll6s1yy5cxl5

**Comment by agonbina** [comment]
@AMO-MTSY I am not really sure the reply answers your question.

I have the exact same question, ie. what if I want to use the prisma binding, ie the old (legacy?!) SDK) instead of the new prisma client in combination with `nexus-prisma`?

The "old SDK" is way more useful and optimized for usage in situations where you want to forward queries/mutations "as is" with some additional pre-processing (ex setting default arguments, or locking down values for specific arguments to the user session). 

Besides that, another drawback shows up when fetching nested relationships (one of the most powerful Prisma features), which is not optimized with the new prisma client as well as it is by using the prisma bindings in combination with fragments. 
Let's take this as an example data model: 
```
type Ship { title: String, user: User! }
type User { ships: [Ship!]! }
```
Say you want to fetch all users and their related ships after you have whitelisted the "users" (or `usersConnection`) query with `nexus-prisma`. What will happen is that this will issue a query for the list of ships (ie `client.users()`) and then an additional query/request for fetching the ships for each user in that list, that is `client.users({ id }).ships()`!

I actually really do not understand what is the reasoning for using the prisma-client versus the prisma binding in the nexus-prisma package which is even officially recommended to be used for building graphql server clients that are typically proxying requests to prisma with some pre/post processing logic.
